sudo: false
language: php
oos:
  - linux
services:
  - mysql
php:
  - 7.2
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS app;'
  - mysql -u root -e "CREATE USER 'app_db_user'@'localhost' IDENTIFIED BY 'app8as3';"
  - mysql -u root -e "GRANT ALL ON app.* TO 'app_db_user'@'localhost';"
before_script:
  - composer self-update
  - composer install --prefer-dist
  - vendor/bin/doctrine orm:schema-tool:update --force
  - bin/common-schema raise:build  

script: vendor/bin/phpunit
notifications:
  email: false
