version: '3.3'
services:
    php-fpm:
        image: gpupo/container-orchestration:symfony-dev-${TAG_VERSION}
        env_file:
            - .env
        volumes:
            - $PWD/:/var/www/app
    mariadb:
        image: mariadb
        restart: always
        expose:
          - 3306
        env_file:
            - .env
