version: '2'
services:
    php-dev:
        container_name: php-dev
        image: gpupo/container-orchestration:php-dev
        volumes:
            - ./:/var/www/app
    mariadb:
        image: mariadb
        restart: always
        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: mas7er
          MYSQL_USER: app_db_user
          MYSQL_PASSWORD: app8as3
          MYSQL_DATABASE: app
