# deleted_at metadata
Gpupo\CommonSchema\ORM\Entity\Application\API\OAuth\Provider:
  type: entity
  table: cs_application_API_OAuth_provider
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Application\API\OAuth\ProviderRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    created_at:
      type: datetime
      nullable: true
      options: {  }
    deleted_at:
      type: datetime
      nullable: true
      options: {  }
    description:
      type: string
      lenght: 50
      unique: false
      nullable: true
      options: {  }
    enabled:
      type: boolean
      nullable: true
      options: {  }
    endpoint:
      type: string
      lenght: 50
      unique: false
      nullable: true
      options: {  }
    environment:
      type: string
      lenght: 50
      unique: false
      nullable: true
      options: {  }
    expands:
      type: array
      nullable: true
      options: {  }
    name:
      type: string
      lenght: 50
      unique: false
      nullable: true
      options: {  }
    status:
      type: string
      lenght: 50
      unique: false
      nullable: true
      options: {  }
    updated_at:
      type: datetime
      nullable: true
      options: {  }
    version:
      type: string
      lenght: 50
      unique: false
      nullable: true
      options: {  }
  oneToMany:
    clients:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Application\API\OAuth\Client\Client
      cascade:
        - persist
        - remove
      options: {  }
      mappedBy: provider
  uniqueConstraints: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
