# deleted_at metadata
Gpupo\CommonSchema\ORM\Entity\Application\API\OAuth\Client\Client:
  type: entity
  table: cs_application_API_OAuth_client
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Application\API\OAuth\Client\ClientRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    client_id:
      type: string
      lenght: 50
      unique: false
      nullable: true
      options: {  }
    client_secret:
      type: string
      lenght: 50
      unique: false
      nullable: true
      options: {  }
    created_at:
      type: datetime
      nullable: true
      options: {  }
    deleted_at:
      type: datetime
      nullable: true
      options: {  }
    description:
      type: string
      lenght: 50
      unique: false
      nullable: true
      options: {  }
    expands:
      type: array
      nullable: true
      options: {  }
    internal_id:
      type: bigint
      nullable: true
      options: {  }
    name:
      type: string
      lenght: 50
      unique: false
      nullable: true
      options: {  }
    status:
      type: string
      lenght: 50
      unique: false
      nullable: true
      options: {  }
    updated_at:
      type: datetime
      nullable: true
      options: {  }
  oneToOne:
    access_token:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Application\API\OAuth\Client\AccessToken
      cascade:
        - persist
        - remove
      options: {  }
      mappedBy: client
  uniqueConstraints:
    client_id_internal_id_idx:
      columns:
        - client_id
        - internal_id
  manyToOne:
    provider:
      cascade:
        - persist
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Application\API\OAuth\Provider
      inversedBy: clients
      joinColumn:
        name: provider_id
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
